### ISSUE TITLE
compilation of crackNum fails on Ubuntu 20.04

### ISSUE THREAD

**Issue by twobombs** [LeventErkok/crackNum#6] opened 2022-08-07 19:18 UTC
Until two weeks ago I could build crackNum straight from [github](https://github.com/LeventErkok/crackNum.git) without fail. When building today I was greeted with the following error:
![Screenshot from 2022-08-07 19-12-23](https://user-images.githubusercontent.com/12692227/183307300-62b19644-930a-47dc-9f71-7850f82ae59a.png)
code that is executed is 
`RUN cd crackNum && stack path --local-bin && stack setup && stack init && stack build && stack install && stack clean && rm -R /crackNum`  [here](https://github.com/twobombs/thereminq-bonsai/blob/cadb4a1dd67ca7b0dbaa8d1570ea36784354ccee/Dockerfiles/Dockerfile#L20)

It mentiones the returned value is a value, not a string. Any idea here ?

**Comment by LeventErkok** [comment] 2022-08-07 19:36
As you noted, crackNum hasn’t changed in quite some time and there were no new releases. So this must have something to do with either stack or ghc. Nothing jumps at me at first look though, as I don’t use stack. 

I’d check if you can install it via plain cabal, or see if you have similar problems with other hackage packages. 

I’ll close this ticket since it doesn’t seem to have anything to do with CrackNum, sorry for not being helpful. If you do tack it down to some root cause I’d like to know. (Or, if it is indeed a crackNum issue, feel free to open a new ticket.)

**Closed as completed by LeventErkok** 2022-08-07 19:36 UTC
